name: Build, Test, and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # --- TESTING SECTION ---
      - name: Run HTML validation
        run: |
            npm install -g html-validator-cli
            html-validator --file index.html --verbose

      - name: Check broken links
        uses: lycheeverse/lychee-action@v1
        with:
            file: ./index.html
      
      - name: Update npm and install modern dependencies
        run: |
            npm install -g npm@latest
            npm install -g @lhci/cli@latest lighthouserc@latest

      - name: Audit with Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
            urls: |
                http://localhost:3000
                temporaryPublicUrl: true
                configPath: ./.github/lighthouserc.json
                budgetPath: ./.github/lighthouse-budget.json

      # --- BUILD & DEPLOY ---
      - name: Build project
        run: |
          mkdir -p dist
          cp -r *.html assets/ dist/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          full_commit_message: "Deploy to GitHub Pages (via GitHub Actions)"
          force_orphan: true